name: vizmo_api
description: Assignment for Vizmo.
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies: 
  foundation_flutter: ^0.2.0
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  very_good_analysis: ^2.4.0
  

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.0.3
  freezed: ^1.1.1
  json_serializable: ^6.0.0
  test: ^1.16.4
