name: outshade_assignment
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.0
  cached_network_image: ^3.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^7.1.0
  intl: ^0.17.0
  path_provider: ^2.0.5
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^8.3.0
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  json_serializable: ^5.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0


flutter:
  uses-material-design: true
  generate: true