name: outshade_assignment

on: [pull_request, push]

env:
  JAVA_VERSION: "11.x"
  FLUTTER_VERSION: "2.5.3"
  FLUTTER_CHANNEL: "stable"
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
          
          
#       # Creating the key.properties file
#       - run: |
#           echo keyPassword=\${{ secrets.KEY_STORE }} > ${{env.PROPERTIES_PATH}}
#           echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
#           echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
#       # Decoding base64 key into a file
#       - run: echo "${{ secrets.KEYSTORE2 }}" | base64 --decode > android/app/key.jks
      
      
      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format lib test
        
      - name: Build apk and upload 
        run: flutter build apk --flavor production --target lib/main_production.dart

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-production-release.apk

# To test and check coverage
#       - name: Analyze
#         run: flutter analyze lib test

#       - name: Run tests
#         run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

#       - name: Check Code Coverage
#         uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
